/* eslint-disable */
// Do not edit this file, it is auto-generated at build time!
// See scripts/bootstrap.js to modify the generation of this file.
module.exports = {
  "sitecoreApiKey": "{5339D3FA-E63B-4FFF-9349-CC2C76413C47}",
  "sitecoreApiHost": "http://localhost:3000",
  "jssAppName": "dinocore",
  "defaultLanguage": "en",
  "graphQLEndpointPath": "/api/dinocore",
  "graphQLEndpoint": "http://localhost:3000/api/dinocore?sc_apikey={5339D3FA-E63B-4FFF-9349-CC2C76413C47}"
};